### PR TITLE
Feat: Implement page project at /project

### PR DESCRIPTION
**Pull request by Yan2arb4**
Project: Page layout and styling done
showcase (video and links), languages and description will need to be adjusted.
Placeholder image for video showcase
Actual SVGs used for languages

### CODE REVIEW

**Review by Brochua — APPROVED** [review]
Looks good for now, will have to be updated once database is implemented to receive an id of sort so we can query the api for the info and move this page to /project/:id

**Comment by Brochua** [comment]
@Sprytte @RiChaarani Can you please review this?

**Review by RiChaarani — APPROVED** [review]
Looks good. I tried adding a bunch of languages and it still look good. 
bunchlogo

**Review by Sprytte — APPROVED** [review]
Looks nice and includes the relevant information. Could add a feature when hovering over the languages to display the name since not everyone is familiar with the logos

**Pull request merged**
