### PR TITLE
Add Jsdoc eslint and bundle size reporting

### PR DESCRIPTION
**Pull request by Brochua**
Add eslint rule to require jsdoc comments for each function.
Add bundle size CI job to frontend ci

### CODE REVIEW

**Review by Yan2arb4 — APPROVED** [review]
Looks good (no idea whats going on)

**Review by Sprytte — APPROVED** [review]
Looks good, though what's up with all those identical warnings?

**Review by noahGelinas — APPROVED** [review]
Great job I think! (There’s tons of coverage reports)

**Review by RiChaarani — APPROVED** [review]
Looks great! Bundle size wasn't that important dont worry

**Pull request merged**
